@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
System(algorithm, "Sentiment Analysis", "Analysing the Comments of Fetched Videos")
Container(dataset, "Youtube Dataset", "Accessed using API")
Container(output, "Output", "Most Recognised Videos")

Rel(user, dataset, "contains")
Rel(user, algorithm, "Analysing the Comments")
Rel(algorithm, output,"Analyse the Sentiment Scores")
@enduml